### ISSUE TITLE
Missing CORS header

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/registry-deploy-testenv#1]
When I try to access `http://environment-registry.epimorphics.net/registry/def/test/` from my browser via the wireframe app, I get:

    XMLHttpRequest cannot load http://environment-registry.epimorphics.net/registry/def/test/. 
    No 'Access-Control-Allow-Origin' header is present on the requested resource. 
    Origin 'http://localhost:8080' is therefore not allowed access.

**Comment by der** [comment]
Have added our standard CORS negotiation component and redeployed. Please could you check if it works for you now?

**Comment by ijdickinson** [comment]
Confirm I can access the endpoint cross-origin now, thanks @der.
