### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/registry-deploy-testenv#3]
Tony reports an issue with the formatting of the page. It looks from the screenshot that the floating menu is not working correctly on some browsers.

![formatting issues](https://user-images.githubusercontent.com/63979/27536731-5bf34d6c-5a68-11e7-8be8-0406c26f2cfd.jpg)

**Comment by ijdickinson** [comment]
I have asked for more details of browser etc

**Comment by der** [comment]
Failed to reproduce using Chrome, Firefox and IE (Edge). Tried different window sizes down to very narrow and tried on Android phone.

**Comment by ijdickinson** [comment]
Closing as obsolete
