### ISSUE TITLE
GDS compliance tweaks

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/registry-deploy-testenv#5]
The background to all phase tags is now `$govuk-blue` (i.e. `#005ea5`). 

The top-bar colour for all Defra sites, including the EA, should be:

    $department-for-environment-food-rural-affairs: #00a33b;

**Comment by der** [comment]
Sorry, don't understand. This is the registry which had previous been approved using the blue phase tag. Has there been some request from Defra to change it?

**Comment by ijdickinson** [comment]
The phase tags changed to use only blue as a background about 6 months ago, because the white-on-orange colour scheme fails a WCAG colour-contrast check. https://govuk-elements.herokuapp.com/alpha-beta-banners/

The use of the green colour bar for all Defra sites was a policy change that was actually made two years ago, but EA are now being told to enforce that ruling. Or, so I was told when we were doing this year's BWQ refresh.

**Comment by der** [comment]
Done.

[Messed up the commit link so manually closing.]
